### ISSUE TITLE
Symbols as name attribute broken with chef-client 12.5

### ISSUE THREAD

**Issue by FreakyDug** [gofullstack/backup-cookbook#35]
With chef-client 12.5, if you try to do this:

```
backup_model :jenkins_home do
  ...
end
```
You get:
```
ERROR: Option name must be a kind of [Symbol]!  You passed "jenkins_home".
```
@vancluever raised this as an issue (https://github.com/chef/chef/issues/4047) in the chef repo and confirmed its a problem with this cookbook.

**Comment by hernan82arg** [comment]
Are you guys working to fix this? I'm upgrading chef-client soon. Thanks
